---
  - name: json parsing
    hosts: localhost
    gather_facts: no
    collections:
      - community.general
    vars:
      input: "{{ lookup('file', 'files/insights.json') | from_json }}"

    tasks:
    
    - name: Create a CVE dictionary
      ansible.builtin.set_fact:
        cves: "{{ input.json.data }}"

    - name: Print out cves
      ansible.builtin.debug:
        var: cves

    - name: Print out flatten cves input
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.utils.to_paths', cves) }}"

    - name: Create cves dictionary (this is now per cve)
      ansible.builtin.set_fact:
        my_cve_dictionary: "{{ cves | json_query('*.id') }}"

    - name: Print out neighbors
      ansible.builtin.debug:
        msg: "{{ my_cve_dictionary }}"
