---
  - name: Go down the JSON file 2 levels
    hosts: localhost
    gather_facts: no
    vars:
      input: "{{ lookup('file', 'files/insights.json') | from_json }}"

    tasks:
    
    - name: Create a CVE Dictionary
      ansible.builtin.set_fact:
        cves: "{{ input.json.data }}"

    - name: Print out cves
      ansible.builtin.debug:
        var: cves

    - name: Print out flattend cves input
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.utils.to_paths', cves) }}"

    - name: Create cves dictionary (this is now per cve)
      ansible.builtin.set_fact:
        my_cve_dictionary: "{{ cves | community.general.json_query('*.id') }}"

    - name: Print out cves
      ansible.builtin.debug:
        msg: "{{ my_cve_dictionary }}"
