---
  - name: Get the list of CVEs related to the server
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: Get my list of CVEs
      register: my_cve_list
      ignore_errors: true
      no_log: true
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/systems/{{ my_insights_inventory_id }}/cves"
        method: GET
        user: "{{ insights_username }}"
        password: "{{ insights_password }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 200
        return_content: yes 
        headers:
          Content-Type: "application/json"

    - name: Print out selected items foreach cve from the input variable
      loop: "{{ my_cve_list['json']['data'] }}"
      ansible.builtin.debug:
        msg: "CVE ID: vulnerabilities:{{ item.attributes.synopsis }}->
              CVE Short Description: {{ item.attributes.rule.description }}->
              CVE Summary: {{ item.attributes.rule.summary }}->
              Reboot Required: {{ item.attributes.rule.reboot_required }}->
              Playbook Count: {{ item.attributes.rule.playbook_count }}->
              Generate Playbook: {{ item.attributes.rule.generate_autoplaybook }}->
              Knowledge Base ID: {{ item.attributes.rule.kbase_node_id }}->
              Rule ID: {{ item.attributes.rule.rule_id }}"