---
  - name: Get the list of CVEs related to the server
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: Get my list of CVEs
      register: my_cve_list
      ignore_errors: true
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/systems/{{ my_insights_inventory_id }}/cves"
        method: GET
        user: "{{ insights_username }}"
        password: "{{ insights_password }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 200
        return_content: yes 
        headers:
          Content-Type: "application/json"

    - name: Print out selected items foreach cve from the input variable
      loop: "{{ my_cve_list['json']['data'] }}"
      ansible.builtin.debug:
        msg: "CVE ID: vulnerabilities:{{ item.attributes.synopsis }}->
              CVE Description: {{ item.attributes.description }}->
              Remediation: {{ item.attributes.remediation }}"

    # - name: Print out flattend input variable
    #   ansible.builtin.debug:
    #     msg: "{{ lookup('ansible.utils.to_paths', my_cve_list) }}"

    # - name: Print out my_cve_list
    #   ansible.builtin.debug:
    #     msg: "{{ my_cve_list }}"