---
  - name: Get the list of hosts registered in Insights
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: Get my list
      register: my_host_list
      ignore_errors: true
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/inventory/v1/hosts?display_name={{ my_server }}"
        method: GET
        user: "{{ insights_username }}"
        password: "{{ insights_password }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 200
        return_content: yes 
        headers:
          Content-Type: "application/json"

    - name: Print out my_insights_ids
      ansible.builtin.debug:
        msg: "{{ my_host_list.json.results[0].id }}"