---
- name: Installing and Registering Red Hat Insights on a server
  hosts: "{{ my_server }}"
  become: yes
  gather_facts: no

  tasks:

  - name: Making sure the packages we are need are installed.
    ansible.builtin.dnf:
      name:
        - insights-client
      state: latest

  - name: Register the insights client
    redhat.insights.insights_register:
      state: present
