---
- name: Installing and Registering Red Hat Insights on a server
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
  
  - name: Making sure the packages we are need are installed.
    ansible.builtin.yum:
      name: 
        - insights-client
      state: present
  
  - name: Register the insights client
    redhat.insights.insights_register:
      state: present
