---
  - name: Get the list of CVEs related to the server
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
      - chg_tasks: ''
      - chg_tasks_dict: {}

    tasks:

    - name: Get my list of CVEs
      register: my_cve_list
      ignore_errors: true
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/systems/{{ my_insights_inventory_id }}/cves"
        method: GET
        user: "{{ insights_username }}"
        password: "{{ insights_password }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 200
        return_content: yes 
        headers:
          Content-Type: "application/json"
    
    - name: Create a change task for each cve with a playbook
      register: task_numbers_are_here
      loop: "{{ my_cve_list['json']['data'] }}"
      when: item.attributes.remediation == 2
      servicenow.itsm.change_request_task:
        configuration_item: "{{ my_server }}"
        change_request_number: "{{ ticket_number }}"
        type: implementation
        state: open
        assigned_to: "hercules"
        assignment_group: "Ansible West Tigers"
        short_description: "vulnerabilities:{{ item.attributes.synopsis }} on Red Hat Insights Inventory ID: {{ my_insights_inventory_id }}"
        description: "{{ item.attributes.description }}"
        on_hold: true
        hold_reason: "Waiting for Ansible Automation Platform to run the remediation playbook."
        other:
          approval: approved

    - name: Create problem for each cve without a playbook
      register: problem_numbers_are_here
      loop: "{{ my_cve_list['json']['data'] }}"
      when: item.attributes.remediation != 2
      servicenow.itsm.problem:
        state: new
        short_description: "Red Hat Insights vulnerabilities:{{ item.attributes.synopsis }} there is no available Ansible Playbook :-0"
        description: "{{ item.attributes.description }}"
        impact: medium
        urgency: low
        other:
          user_input: "Red Hat Insights Inventory ID: {{ my_insights_inventory_id }}"

    - name: Update a fact for change ticket task numbers; white space delimited
      loop: "{{ task_numbers_are_here['results'] }}"
      when: item.changed != false
      ansible.builtin.set_fact:
        chg_tasks: "{{ chg_tasks + item.record.number }} "
    
    - name: Retrieve change request tasks by number
      register: task_info_here
      loop: "{{ (chg_tasks.split()) }}"
      servicenow.itsm.change_request_task_info:
        number: "{{ item }}"

    # - name: what is this anyway
    #   debug:
    #     msg: "{{ task_info_here | type_debug }}"

    # - name: print out my dictionary
    #   debug:
    #     msg: "{{ task_info_here }}"

    - name: Print out task_info_here
      loop: "{{ lookup('ansible.builtin.dict', task_info_here) }}"
      when: item.key == "results"
      ansible.builtin.debug:
        msg: "{{ item }}"