---
  - name: Get the list of CVEs related to the server
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
      chg_tasks: ''

    tasks:

    - name: Get my list of CVEs
      register: my_cve_list
      ignore_errors: true
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/systems/{{ my_insights_inventory_id }}/cves"
        method: GET
        user: "{{ insights_username }}"
        password: "{{ insights_password }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 200
        return_content: yes 
        headers:
          Content-Type: "application/json"

    # - name: Print out selected items foreach cve from the input variable
    #   loop: "{{ my_cve_list['json']['data'] }}"
    #   ansible.builtin.debug:
    #     msg: "CVE ID: vulnerabilities:{{ item.attributes.synopsis }}->
    #           CVE Description: {{ item.attributes.description }}->
    #           Remediation: {{ item.attributes.remediation }}"
    
    - name: Create a change task for each cve with a playbook
      register: task_numbers_are_here
      loop: "{{ my_cve_list['json']['data'] }}"
      when: item.attributes.remediation == 2
      servicenow.itsm.change_request_task:
        configuration_item: "{{ my_server }}"
        change_request_number: "{{ ticket_number }}"
        type: implementation
        state: open
        assigned_to: "hercules"
        assignment_group: "Ansible West Tigers"
        short_description: "vulnerabilities:{{ item.attributes.synopsis }} on Red Hat Insights Inventory ID: {{ my_insights_inventory_id }}"
        description: "{{ item.attributes.description }}"
        on_hold: true
        hold_reason: "Waiting for Ansible Automation Platform to run the remediation playbook."
        other:
          approval: approved

    - name: Create problem for each cve without a playbook
      register: problem_numbers_are_here
      loop: "{{ my_cve_list['json']['data'] }}"
      when: item.attributes.remediation != 2
      servicenow.itsm.problem:
        state: new
        short_description: "Red Hat Insights vulnerabilities:{{ item.attributes.synopsis }} exists on {{ my_server }} and there is no available Ansible Playbook :-0"
        description: "{{ item.attributes.description }}"
        impact: medium
        urgency: low
        other:
          user_input: "Red Hat Insights Inventory ID: {{ my_insights_inventory_id }}"

    # - name: is this a list?
    #   ansible.builtin.debug:
    #     var: "{{ my_cve_list | type_debug }}"
    

    # - name: Print out task_numbers_are_here
    #   loop: "{{ task_numbers_are_here['results'] }}"
    #   ansible.builtin.debug:
    #     msg: "{{ item.record.number }}"


    - name: Set a fact for change ticket task numbers
      loop: "{{ task_numbers_are_here['results'] }}"
      ansible.builtin.set_fact:
        chg_tasks: "{{ chg_tasks + item.record.number }}:"
    
    - name: Print
      ansible.builtin.debug:
        msg: "{{ chg_tasks }}"