---
  - name: Remediate the CVEs
    hosts: localhost
    connection: local
    gather_facts: no
    
    tasks:

    - name: print my_playbooks stadard out
      loop: "{{ my_playbooks['results'] }}"
      ansible.builtin.debug:
        msg: "{{item.item.number}} {{ item.content.split('\n') }}"