---
- name: "Update job template for template id {{ project_id }}"
  ansible.builtin.uri:
    url: "https://{{ controller_url }}/api/v2/job_templates/165/?name=Insights%20CVE%20T1000%20\"The%20Remediator\""
    method: PATCH
    headers:
      Authorization: "Bearer {{ new_token.json.token }}"
      Content-Type: "application/json"
    validate_certs: no
    follow_redirects: all
    return_content: no
    body_format: json
    body: "{{ lookup('ansible.builtin.template','templates/job_template_body.j2') }}"
    status_code: 200

- name: Run job template
  register: my_job_info
  ansible.builtin.uri:
    url: "https://{{ controller_url }}/api/v2/job_templates/165/launch/"
    method: POST
    headers:
      Authorization: "Bearer {{ new_token.json.token }}"
      Content-Type: "application/json"
    validate_certs: no
    follow_redirects: all
    return_content: no
    status_code: 201

- name: print job id
  debug:
    msg: "{{ my_job_info.josn.id }}"

# - name: Update the change task ticket 
#   servicenow.itsm.change_request_task:
#     on_hold: false
#     state: "closed"
#     number: "{{ item.number }}"
#     close_code: "successful"
#     close_notes: "hoo-yah"
#     other:
#       work_notes: "all done"

- name: Update job template back to default playbook
  ansible.builtin.uri:
    url: "https://{{ controller_url }}/api/v2/job_templates/165/?name=Insights%20CVE%20T1000%20\"The%20Remediator\""
    method: PATCH
    headers:
      Authorization: "Bearer {{ new_token.json.token }}"
      Content-Type: "application/json"
    validate_certs: no
    follow_redirects: all
    return_content: no
    body_format: json
    body: "{{ lookup('ansible.builtin.template','templates/job_template_body_default.j2') }}"
    status_code: 200

- name: Pausing for 10 seconds to allow for the project up to finish
  ansible.builtin.pause:
    seconds: 60

#- name: Delete playbook from repository